name: "Terraform CI/CD Pipeline"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: "Terraform Apply"
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      # 1. Clone the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      # 3. Authenticate with Azure using OIDC (secure method)
      - name: "Login to Azure"
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # 4. Initialize Terraform Backend (Azure Storage)
      - name: Terraform Init
        run: terraform init

      # 5. Check code formatting standards
      - name: Terraform Format Check
        run: terraform fmt -check

      # 6. Validate the Terraform configuration for errors
      - name: Terraform Validate
        run: terraform validate

      # 7. Run terraform plan to preview changes
      - name: Terraform Plan
        run: terraform plan
        continue-on-error: false

      # 8. Deploy to Azure when committing to main branch
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve